// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScheduleApp.Models;

public partial class Cabinet
{
    public int IdCabinet { get; set; }

    public string NameCabinet { get; set; }

    public int? IdType { get; set; }

    public virtual CabinetType IdTypeNavigation { get; set; }

    public virtual ICollection<Pair> Pairs { get; set; } = new List<Pair>();

    public string DisplayProperty => $"Cabinet: {NameCabinet} (Type: {IdTypeNavigation.TypeCabinet})";
}