// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScheduleApp.Models;

public partial class Cabinettype
{
    public int IdType { get; set; }

    public string TypeCabinet { get; set; }

    public virtual ICollection<Cabinet> Cabinets { get; set; } = new List<Cabinet>();
    public string DisplayProperty => $"(Type: {TypeCabinet})";

}