// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScheduleApp.Models;

public partial class NumberPair
{
    public int Id { get; set; }

    public int? NumberPair1 { get; set; }

    public virtual ICollection<Pair> Pairs { get; set; } = new List<Pair>();
}