// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScheduleApp.Models;

public partial class Pair
{
    public int IdPair { get; set; }

    public int IdTeacher { get; set; }

    public int IdCabinet { get; set; }

    public int IdGroup { get; set; }

    public int IdDay { get; set; }

    public int IdTypeLesson { get; set; }

    public int IdSubject { get; set; }

    public int IdSheduleNumber { get; set; }

    public DateOnly? Date { get; set; }

    public virtual Cabinet IdCabinetNavigation { get; set; }

    public virtual Day IdDayNavigation { get; set; }

    public virtual StudentGroup IdGroupNavigation { get; set; }

    public virtual Subject IdSubjectNavigation { get; set; }

    public virtual Teacher IdTeacherNavigation { get; set; }

    public virtual SubjectLesson IdTypeLessonNavigation { get; set; }
}