// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScheduleApp.Models;

public partial class StudentGroup
{
    public int IdGroup { get; set; }

    public string NameGroup { get; set; }

    public string Course { get; set; }

    public virtual ICollection<Pair> Pairs { get; set; } = new List<Pair>();
}