// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ScheduleApp.Models;

public partial class Teacher
{
    public int IdTeacher { get; set; }

    public string NameTeacher { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Pair> Pairs { get; set; } = new List<Pair>();
}