// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Semester
{
    public int IdSemester { get; set; }

    public int NumberSemester { get; set; }

    public virtual ICollection<Week> Weeks { get; set; } = new List<Week>();
}